### ISSUE TITLE
unbreak nightlies

### ISSUE THREAD

**Issue by Lotterleben** [knurling-rs/flip-link#13]
Our nightlies are failing: https://github.com/knurling-rs/flip-link/actions because our app-template patch doesn't apply anymore.This will likely break every time we update the app-template.. maybe we can come up with a less brittle way to modify the TODOs in the template?

**Comment by Lotterleben** [comment]
also, related: Am I the only one who gehts e-mails about broken nightlies in their inbox? bc I think they should end up in the knurling e-mail inbox or our zulip stream. @jonas-schievink @japaric

**Comment by jonas-schievink** [comment]
I have all GitHub emails turned off, and apparently failing cron jobs don't send regular GitHub notifications.

Why are we testing the app-template in the flip-link repo? Would it maybe make more sense to move this job to the app-template repo? flip-link could also be tested by building a fixed app instead of patching the template.

**Comment by Lotterleben** [comment]
grmbl, that's unfortunate :( (I see why you'd turn off all github emails though :D I can add a rule to forward these to tour knurling address)

we're not fully testing the app-template, just setting up an app using the template to check if flip-link compiles. building a fixed app is probably the less brittle approach here... should we add one as an example to this repo (seems like weird overhead but maybe also good to demonstrate how easy it is to incorporate flip-link? :D) or maintain it in a dedicated knurling repo? I'm kind of leaning towards the former

**Comment by jonas-schievink** [comment]
Yeah a separate repo doesn't sound like the right approach here – this is primarily just for testing flip-link after all

**Comment by japaric** [comment]
> I have all GitHub emails turned off

(same)

> building a fixed app is probably the less brittle approach here

I vote for committing a small firmware project into this repo. It could even be an instance of the cortex-m-quickstart template instead of the knurling one. We want to test that flip-link works with cortex-m-rt applications so it's not necessary to have the firmware depend on defmt. We should also have the firmware project use the `lm3s6965` crate instead of a fully fledged HAL to reduce CI time.
